import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import fs from 'node:fs';
fs.mkdirSync('.sites-runtime',{recursive:true});fs.writeFileSync('.sites-runtime/domain-test.mjs',ts.transpileModule(fs.readFileSync('app/domain.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {emptyState,apply,totals,today,invoiceMissing}=await import('../.sites-runtime/domain-test.mjs');
const customer={id:'c1',name:'Testkunde',street:'Teststraße 1',zip:'20095',city:'Hamburg',country:'DE',phone:'',email:'',vatId:''};
const line={id:'l1',description:'Testbrot',qty:3,unit:'Stück',price:125,tax:7,discount:10};
const order={id:'o1',customerId:'c1',date:today(),deliveryDate:today(),route:'',employeeId:'',status:'new',notes:'',lines:[line]};
const invoice={id:'i1',customerId:'c1',orderId:'o1',date:today(),deliveryDate:today(),dueDate:today(),notes:'',exemption:'',lines:[line],number:'',status:'draft',kind:'invoice',originalId:'',company:null,buyer:null};
function prepared(){let s=structuredClone(emptyState);s=apply(s,{action:'save',kind:'customers',record:customer});s=apply(s,{action:'save',kind:'orders',record:order});s=apply(s,{action:'save',kind:'invoices',record:invoice});s=apply(s,{action:'saveCompany',record:{...s.company,name:'Test GmbH',street:'Teststraße 2',zip:'20095',city:'Hamburg',country:'DE',taxId:'TEST',logo:'/api/logo/test.png',seat:'Hamburg',court:'Amtsgericht Hamburg',register:'HRB TEST',director:'Test Person'}});return s}
test('empty workspace has no seeded business records',()=>{for(const key of ['orders','customers','employees','stock','invoices','payments'])assert.equal(emptyState[key].length,0);assert.equal(emptyState.company.name,'')});
test('money: discount per line and VAT grouped by tax rate',()=>{const t=totals([line,{...line,id:'l2',qty:1,price:1000,tax:19,discount:0}]);assert.equal(t.net,1338);assert.equal(t.tax,214);assert.equal(t.gross,1552);assert.equal(t.groups['7'].net,338)});
test('customer and employee CRUD, stable identity, referenced deletion protected',()=>{let s=prepared();s=apply(s,{action:'save',kind:'customers',record:{...customer,name:'Geändert'}});assert.equal(s.orders[0].customerId,'c1');assert.equal(s.customers[0].name,'Geändert');assert.throws(()=>apply(s,{action:'delete',kind:'customers',id:'c1'}));const e={id:'e1',name:'Test',role:'Fahrer',phone:'',email:'',active:true};s=apply(s,{action:'save',kind:'employees',record:e});s=apply(s,{action:'save',kind:'employees',record:{...e,active:false}});assert.equal(s.employees[0].active,false);s=apply(s,{action:'delete',kind:'employees',id:'e1'});assert.equal(s.employees.length,0)});
test('invoice issue validates fields, freezes snapshots and prevents overwrite/deletion',()=>{let s=prepared();assert.deepEqual(invoiceMissing(s.invoices[0],s.company,s.customers[0]),[]);assert.throws(()=>apply({...s,company:{...s.company,taxId:''}},{action:'issue',id:'i1'}));s=apply(s,{action:'issue',id:'i1'});assert.equal(s.invoices[0].number,`RE-${today().slice(0,4)}-000001`);const snapshot=s.invoices[0].buyer.name;s=apply(s,{action:'save',kind:'customers',record:{...customer,name:'New Name'}});assert.equal(s.invoices[0].buyer.name,snapshot);assert.throws(()=>apply(s,{action:'delete',kind:'invoices',id:'i1'}));assert.throws(()=>apply(s,{action:'save',kind:'invoices',record:invoice}));s=apply(s,{action:'save',kind:'orders',record:{...order,status:'delivered'}});assert.equal(s.orders[0].status,'delivered');assert.throws(()=>apply(s,{action:'save',kind:'orders',record:{...order,lines:[{...line,price:999}]}}))});
test('payment bounds, correction reason, reversal and cancellation numbering',()=>{let s=apply(prepared(),{action:'issue',id:'i1'});assert.throws(()=>apply(s,{action:'payment',invoiceId:'i1',amount:999999,date:today(),method:'cash'}));s=apply(s,{action:'payment',invoiceId:'i1',amount:100,date:today(),method:'cash'});assert.throws(()=>apply(s,{action:'cancel',id:'i1',reason:'Korrektur'}));s=apply(s,{action:'reversePayment',id:s.payments[0].id,reason:'Fehlbuchung'});s=apply(s,{action:'cancel',id:'i1',reason:'Korrektur'});assert.equal(s.invoices.find(i=>i.id==='i1').status,'cancelled');assert.equal(s.invoices[0].kind,'cancellation');assert.equal(s.invoices[0].number,`ST-${today().slice(0,4)}-000002`);assert.equal(s.invoices[0].originalId,'i1');assert.throws(()=>apply(s,{action:'issue',id:'i1'}))});
test('draft deletion and missing tax-exemption validation',()=>{let s=prepared();assert.throws(()=>apply(s,{action:'save',kind:'invoices',record:{...invoice,id:'i2'}}));s=apply(s,{action:'delete',kind:'invoices',id:'i1'});assert.equal(s.invoices.length,0);assert.ok(invoiceMissing({...invoice,lines:[{...line,tax:0}]},s.company,customer).includes('Grund der Steuerbefreiung'))});
test('line identifiers, discount precision and malformed record identifiers are rejected',()=>{let s=prepared();assert.throws(()=>apply(s,{action:'save',kind:'orders',record:{...order,lines:[line,line]}}));assert.throws(()=>apply(s,{action:'save',kind:'orders',record:{...order,lines:[{...line,discount:1.234}]}}));assert.throws(()=>apply(s,{action:'save',kind:'customers',record:{...customer,id:'../../test'}}))});
test('linked draft customer cannot be silently invalidated',()=>{let s=prepared();s=apply(s,{action:'save',kind:'customers',record:{...customer,id:'c2'}});assert.throws(()=>apply(s,{action:'save',kind:'orders',record:{...order,customerId:'c2'}}))});
test('cent rounding is stable for fractional quantities and half-cent discounts',()=>{assert.equal(totals([{...line,qty:1,price:100,discount:5.5,tax:0}]).net,95);assert.equal(totals([{...line,qty:0.1,price:105,discount:0,tax:0}]).net,11)});
