import {z} from 'zod';
const text=z.string().trim().max(250),id=z.string().regex(/^[A-Za-z0-9_-]{1,100}$/),date=z.string().refine(v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Ungültiges Datum');
const optionalDate=z.union([z.literal(''),date]);
export const customerSchema=z.object({id,name:text.min(1),street:text,zip:text,city:text,country:text,phone:text,email:z.union([z.literal(''),z.string().email().max(250)]),vatId:text});
export const employeeSchema=z.object({id,name:text.min(1),role:text,phone:text,email:z.union([z.literal(''),z.string().email().max(250)]),active:z.boolean()});
export const stockSchema=z.object({id,name:text.min(1),qty:z.number().nonnegative().max(1e7),unit:text.min(1),min:z.number().nonnegative().max(1e7)});
export const companySchema=z.object({name:text,street:text,zip:text,city:text,country:text,taxId:text,vatId:text,phone:text,email:text,iban:text,bic:text,bank:text,seat:text,court:text,register:text,director:text,logo:z.string().max(180),smallBusiness:z.boolean(),priorRevenueBelow800k:z.boolean()});
export const lineSchema=z.object({id,description:text.min(1),qty:z.number().positive().max(1e5).refine(v=>Math.abs(v*1000-Math.round(v*1000))<0.00001),unit:text.min(1),price:z.number().int().nonnegative().max(1e8),tax:z.union([z.literal(0),z.literal(7),z.literal(19)]),discount:z.number().min(0).max(100).refine(v=>Math.abs(v*100-Math.round(v*100))<0.00001)});
export const orderSchema=z.object({id,customerId:id,date,deliveryDate:optionalDate,route:text,employeeId:z.string().max(100),status:z.enum(['new','production','ready','delivery','delivered']),notes:z.string().max(2000),lines:z.array(lineSchema).min(1).max(100).refine(ls=>new Set(ls.map(l=>l.id)).size===ls.length,'Positions-IDs müssen eindeutig sein')});
export const invoiceSchema=z.object({id,customerId:id,orderId:z.string().max(100),date,deliveryDate:optionalDate,dueDate:optionalDate,notes:z.string().max(2000),exemption:z.string().max(500),lines:z.array(lineSchema).min(1).max(100).refine(ls=>new Set(ls.map(l=>l.id)).size===ls.length,'Positions-IDs müssen eindeutig sein'),number:z.string(),status:z.enum(['draft','issued','cancelled']),kind:z.enum(['invoice','cancellation']),originalId:z.string(),company:companySchema.nullable(),buyer:customerSchema.nullable()});
export type Customer=z.infer<typeof customerSchema>;export type Employee=z.infer<typeof employeeSchema>;export type Stock=z.infer<typeof stockSchema>;export type Company=z.infer<typeof companySchema>;export type Line=z.infer<typeof lineSchema>;export type Order=z.infer<typeof orderSchema>;export type Invoice=z.infer<typeof invoiceSchema>;
export type Payment={id:string;invoiceId:string;amount:number;date:string;method:string};
export type State={schemaVersion:3;customers:Customer[];employees:Employee[];stock:Stock[];orders:Order[];invoices:Invoice[];payments:Payment[];company:Company;sequence:number;log:{id:string;text:string;time:string}[]};
export const companyEmpty:Company={name:'',street:'',zip:'',city:'',country:'',taxId:'',vatId:'',phone:'',email:'',iban:'',bic:'',bank:'',seat:'',court:'',register:'',director:'',logo:'/shams-logo.jpg',smallBusiness:false,priorRevenueBelow800k:false};
export const emptyState:State={schemaVersion:3,customers:[],employees:[],stock:[],orders:[],invoices:[],payments:[],company:companyEmpty,sequence:0,log:[]};
export const uid=()=>crypto.randomUUID();export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function lineNet(l:Line){const qty=Math.round(l.qty*1000),discount=Math.round(l.discount*100);if(!Number.isFinite(qty)||!Number.isFinite(discount)||!Number.isFinite(l.price))return 0;const numerator=BigInt(qty)*BigInt(Math.round(l.price))*BigInt(10000-discount);return Number((numerator+BigInt(5_000_000))/BigInt(10_000_000))}
export function totals(lines:Line[]){const groups:Record<string,{net:number;tax:number}>={};let net=0;for(const l of lines){const n=lineNet(l);net+=n;(groups[l.tax]??={net:0,tax:0}).net+=n}for(const [rate,g] of Object.entries(groups))g.tax=Math.round(g.net*Number(rate)/100);const tax=Object.values(groups).reduce((n,g)=>n+g.tax,0);return {net,tax,gross:net+tax,groups}}
export const money=(cents:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(cents/100);
export const paid=(s:State,id:string)=>s.payments.filter(p=>p.invoiceId===id).reduce((n,p)=>n+p.amount,0);
export function invoiceMissing(i:Invoice,c:Company,b?:Customer|null){const missing:string[]=[];if(!c.name)missing.push('Firma');if(!c.street||!c.zip||!c.city||!c.country)missing.push('Firmenanschrift');if(!c.taxId&&!c.vatId)missing.push('Steuernummer / USt-IdNr.');if(!b?.name||!b.street||!b.zip||!b.city||!b.country)missing.push('Kundenanschrift');if(!i.deliveryDate)missing.push('Lieferdatum');if(!i.dueDate)missing.push('Fälligkeitsdatum');if(i.dueDate&&i.dueDate<i.date)missing.push('Fälligkeit vor Rechnungsdatum');if(!c.logo)missing.push('Firmenlogo');if(/gmbh|\bug\b/i.test(c.name)&&(!c.seat||!c.court||!c.register||!c.director))missing.push('Sitz, Registergericht, Registernummer, Geschäftsführung');if(i.lines.some(l=>l.tax===0)&&!i.exemption.trim())missing.push('Grund der Steuerbefreiung');if(c.smallBusiness&&i.lines.some(l=>l.tax!==0))missing.push('Kleinunternehmer: Positionen ohne Umsatzsteuer erfassen');if(!i.lines.length)missing.push('Positionen');return missing}
export type Command={action:string;kind?:string;id?:string;record?:unknown;invoiceId?:string;amount?:number;date?:string;method?:string;reason?:string};
export function apply(s:State,cmd:Command):State{const next=structuredClone(s);let event='';const recordId=cmd.id;const collections=['customers','employees','stock','orders','invoices'] as const;type Key=typeof collections[number];const kind=cmd.kind as Key;
 if(cmd.action==='saveCompany'){next.company=companySchema.parse(cmd.record);if(next.company.logo&&!/^\/api\/logo\/[a-zA-Z0-9.-]+$|^\/shams-logo\.(png|jpg|webp)$/.test(next.company.logo))throw Error('Ungültiges Logo');event='Firmendaten aktualisiert';}
 else if(cmd.action==='save'){
  if(!collections.includes(kind))throw Error('Ungültiger Bereich');
  const schemas={customers:customerSchema,employees:employeeSchema,stock:stockSchema,orders:orderSchema,invoices:invoiceSchema};const r=schemas[kind].parse(cmd.record);const old=(s[kind] as {id:string}[]).find(x=>x.id===r.id);
  if(kind==='orders'){const o=r as Order;if(totals(o.lines).gross>100_000_000_000)throw Error('Bestellbetrag zu groß');if(!s.customers.some(c=>c.id===o.customerId))throw Error('Kunde nicht gefunden');if(s.invoices.some(i=>i.orderId===o.id&&i.customerId!==o.customerId))throw Error('Kunde weicht von verknüpfter Rechnung ab');if(o.employeeId&&!s.employees.some(e=>e.id===o.employeeId))throw Error('Mitarbeiter nicht gefunden');if(s.invoices.some(i=>i.orderId===r.id&&i.status!=='draft')&&old){const prev=old as Order;if(JSON.stringify([prev.customerId,prev.lines,prev.date,prev.deliveryDate])!==JSON.stringify([o.customerId,o.lines,o.date,o.deliveryDate]))throw Error('Bereits abgerechnet: Rechnungsrelevante Bestelldaten sind geschützt');}}
  if(kind==='invoices'){const i=r as Invoice;if(!s.customers.some(c=>c.id===i.customerId))throw Error('Kunde nicht gefunden');if(totals(i.lines).gross>100_000_000_000)throw Error('Rechnungsbetrag zu groß');if(i.orderId&&!s.orders.some(o=>o.id===i.orderId&&o.customerId===i.customerId))throw Error('Bestellung passt nicht zum Kunden');if(i.orderId&&s.invoices.some(x=>x.id!==i.id&&x.orderId===i.orderId&&x.kind==='invoice'&&x.status!=='cancelled'))throw Error('Für diese Bestellung existiert bereits eine Rechnung');if((old as Invoice|undefined)?.status&& (old as Invoice).status!=='draft')throw Error('Ausgestellte Rechnung ist unveränderbar');if(i.status!=='draft'||i.number||i.kind!=='invoice'||i.originalId||i.company||i.buyer)throw Error('Nur Entwürfe können bearbeitet werden');}
  (next[kind] as unknown[])=[r,...(next[kind] as {id:string}[]).filter(x=>x.id!==r.id)];event=`${kind}: ${old?'bearbeitet':'angelegt'} · ${r.id}`;
 }
 else if(cmd.action==='delete'){
  if(!collections.includes(kind)||!(s[kind] as {id:string}[]).some(x=>x.id===recordId))throw Error('Eintrag nicht gefunden');
  if(kind==='customers'&&(s.orders.some(o=>o.customerId===recordId)||s.invoices.some(i=>i.customerId===recordId)))throw Error('Kunde ist mit Bestellungen oder Rechnungen verknüpft');
  if(kind==='employees'&&s.orders.some(o=>o.employeeId===recordId))throw Error('Mitarbeiter ist einer Bestellung zugeordnet');
  if(kind==='orders'&&s.invoices.some(i=>i.orderId===recordId))throw Error('Zuerst den verknüpften Rechnungsentwurf löschen. Ausgestellte Rechnungen bleiben erhalten.');
  if(kind==='invoices'&&s.invoices.find(i=>i.id===recordId)?.status!=='draft')throw Error('Nur Entwürfe sind löschbar. Rechnung stattdessen stornieren.');
  (next[kind] as {id:string}[])=(next[kind] as {id:string}[]).filter(x=>x.id!==recordId);event=`${kind}: gelöscht · ${recordId}`;
 }
 else if(cmd.action==='issue'){
  const i=next.invoices.find(x=>x.id===recordId);if(!i||i.status!=='draft')throw Error('Rechnung ist kein Entwurf');if(i.orderId&&!s.orders.some(o=>o.id===i.orderId&&o.customerId===i.customerId))throw Error('Verknüpfte Bestellung und Kunde stimmen nicht überein');const buyer=s.customers.find(c=>c.id===i.customerId);const errors=invoiceMissing(i,s.company,buyer);if(errors.length)throw Error('Bitte ergänzen: '+errors.join(', '));
  // This release issues domestic paper invoices only; do not silently cross e-invoice transition limits.
  if(i.date>today()||i.deliveryDate>today())throw Error('Rechnungs- und Lieferdatum dürfen nicht in der Zukunft liegen');
  if(i.date<'2026-01-01'||today()>'2027-12-31'||(today()>'2026-12-31'&&!s.company.priorRevenueBelow800k&&!s.company.smallBusiness))throw Error('E-Rechnungsfrist prüfen: strukturierte E-Rechnung ist hier noch nicht verfügbar');
  const domestic=(v:string)=>['de','deutschland','germany','ألمانيا'].includes(v.toLowerCase().trim());if(!domestic(s.company.country)||!domestic(buyer!.country))throw Error('Diese Version unterstützt nur inländische Rechnungen');
  i.status='issued';i.number=`RE-${i.date.slice(0,4)}-${String(++next.sequence).padStart(6,'0')}`;i.company=structuredClone(s.company);i.buyer=structuredClone(buyer!);event='Rechnung ausgestellt · '+i.number;
 }
 else if(cmd.action==='cancel'){
  const i=next.invoices.find(x=>x.id===recordId);if(!i||i.status!=='issued'||i.kind!=='invoice')throw Error('Rechnung kann nicht storniert werden');if(paid(s,i.id)>0)throw Error('Zahlungen zuerst nachvollziehbar zurücknehmen');if(!cmd.reason?.trim()||cmd.reason.length>300)throw Error('Stornogrund erforderlich (max. 300 Zeichen)');i.status='cancelled';const cancel:Invoice={...structuredClone(i),id:uid(),number:`ST-${today().slice(0,4)}-${String(++next.sequence).padStart(6,'0')}`,status:'issued',kind:'cancellation',originalId:i.id,date:today(),notes:`Storno zu ${i.number}: ${cmd.reason.trim()}`};next.invoices.unshift(cancel);event='Rechnung storniert · '+i.number+' · '+cmd.reason;
 }
 else if(cmd.action==='payment'){
  const p=z.object({invoiceId:id,amount:z.number().int().positive(),date,method:z.enum(['cash','bank'])}).parse(cmd);const i=s.invoices.find(i=>i.id===p.invoiceId);if(!i||i.status!=='issued'||i.kind!=='invoice')throw Error('Rechnung ist nicht offen');if(p.amount>totals(i.lines).gross-paid(s,i.id))throw Error('Betrag übersteigt den offenen Posten');next.payments.unshift({...p,id:uid()});event='Zahlung · '+i.number+' · '+money(p.amount);
 }
 else if(cmd.action==='reversePayment'){const p=s.payments.find(x=>x.id===recordId);if(!p||!cmd.reason?.trim()||cmd.reason.length>300)throw Error('Zahlung und Begründung erforderlich');next.payments=next.payments.filter(x=>x.id!==recordId);event='Zahlung zurückgenommen · '+money(p.amount)+' · '+recordId+' · '+cmd.reason;}
 else throw Error('Unbekannte Aktion');
 next.log.unshift({id:uid(),text:event,time:new Date().toISOString()});return next;
}
