import {z} from 'zod';
export class RequestError extends Error {constructor(message:string,public status=400){super(message)}}
export function checkOrigin(req:Request){const site=req.headers.get('sec-fetch-site');if(site==='cross-site')throw new RequestError('Ungültiger Ursprung',403);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new RequestError('Ungültiger Ursprung',403)}
export async function readLimited(req:Request,maxBytes:number){const header=req.headers.get('content-length');if(header!==null&&(!/^\d+$/.test(header)||Number(header)>maxBytes))throw new RequestError('Anfrage zu groß',413);if(!req.body)return new Uint8Array();const reader=req.body.getReader();let size=0;const chunks:Uint8Array[]=[];try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new RequestError('Anfrage zu groß',413)}chunks.push(value)}}finally{reader.releaseLock()}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.byteLength}return bytes}
export const envelope=z.object({revision:z.number().int().nonnegative().safe(),command:z.object({action:z.enum(['initialize','save','delete','saveCompany','issue','cancel','payment','reversePayment']),kind:z.enum(['orders','invoices','customers','employees','stock','company']).optional(),id:z.string().max(100).optional(),record:z.unknown().optional(),invoiceId:z.string().max(100).optional(),amount:z.number().int().positive().safe().optional(),date:z.string().max(10).optional(),method:z.enum(['cash','bank']).optional(),reason:z.string().trim().min(1).max(300).optional()}).strict()}).strict();
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}})}
export function requestError(e:unknown){if(e instanceof RequestError)return json({error:e.message},e.status);if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:'Bitte alle Pflichtfelder und Eingaben prüfen.'},400);console.error('Request failed',e instanceof Error?e.name:'UnknownError');return json({error:'Vorgang fehlgeschlagen. Bitte erneut versuchen.'},500)}
export function imageFormat(b:Uint8Array):{type:string;ext:string}|null{
 if(b.length<12)return null;const v=new DataView(b.buffer,b.byteOffset,b.byteLength);const ascii=(a:number,z:number)=>new TextDecoder().decode(b.slice(a,z));const valid=(w:number,h:number)=>w>0&&h>0&&w*h<=16_000_000;
 if(b.length>=45&&[137,80,78,71,13,10,26,10].every((n,i)=>b[i]===n)&&v.getUint32(8)===13&&ascii(12,16)==='IHDR'&&ascii(b.length-8,b.length-4)==='IEND')return valid(v.getUint32(16),v.getUint32(20))?{type:'image/png',ext:'png'}:null;
 if(b[0]===255&&b[1]===216&&b[b.length-2]===255&&b[b.length-1]===217){let p=2;while(p+4<b.length){if(b[p++]!==255)return null;while(b[p]===255)p++;const marker=b[p++];if(marker===217||marker===218)return null;if(marker===1||(marker>=208&&marker<=215))continue;if(p+2>b.length)return null;const length=v.getUint16(p);if(length<2||p+length>b.length)return null;if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){if(length<8)return null;return valid(v.getUint16(p+5),v.getUint16(p+3))?{type:'image/jpeg',ext:'jpg'}:null}p+=length}return null}
 if(ascii(0,4)==='RIFF'&&ascii(8,12)==='WEBP'&&v.getUint32(4,true)+8===b.length){let p=12;while(p+8<=b.length){const type=ascii(p,p+4),size=v.getUint32(p+4,true),d=p+8;if(d+size>b.length)return null;let w=0,h=0;if(type==='VP8X'&&size>=10){w=1+b[d+4]+(b[d+5]<<8)+(b[d+6]<<16);h=1+b[d+7]+(b[d+8]<<8)+(b[d+9]<<16)}else if(type==='VP8L'&&size>=5&&b[d]===47){const n=v.getUint32(d+1,true);w=1+(n&16383);h=1+((n>>>14)&16383)}else if(type==='VP8 '&&size>=10&&b[d+3]===157&&b[d+4]===1&&b[d+5]===42){w=v.getUint16(d+6,true)&16383;h=v.getUint16(d+8,true)&16383}if(w)return valid(w,h)?{type:'image/webp',ext:'webp'}:null;p=d+size+(size%2)}}return null;
}
